# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `cucumber-ci-environment` gem.
# Please instead update this file by running `bin/tapioca gem cucumber-ci-environment`.


# source://cucumber-ci-environment//lib/cucumber/ci_environment/variable_expression.rb#3
module Cucumber
  class << self
    # source://cucumber/10.2.0/lib/cucumber.rb#16
    def deprecate(message, method, remove_after_version); end

    # source://cucumber/10.2.0/lib/cucumber/platform.rb#19
    def file_mode(mode, encoding = T.unsafe(nil)); end

    # source://cucumber/10.2.0/lib/cucumber.rb#24
    def logger; end

    # source://cucumber/10.2.0/lib/cucumber.rb#32
    def logger=(logger); end

    # source://cucumber/10.2.0/lib/cucumber/platform.rb#15
    def use_full_backtrace; end

    # source://cucumber/10.2.0/lib/cucumber/platform.rb#13
    def use_full_backtrace=(_arg0); end

    # source://cucumber/10.2.0/lib/cucumber.rb#14
    def use_legacy_autoloader; end

    # source://cucumber/10.2.0/lib/cucumber.rb#36
    def use_legacy_autoloader=(value); end

    # source://cucumber/10.2.0/lib/cucumber.rb#13
    def wants_to_quit; end

    # source://cucumber/10.2.0/lib/cucumber.rb#13
    def wants_to_quit=(_arg0); end
  end
end

# source://cucumber-ci-environment//lib/cucumber/ci_environment/variable_expression.rb#4
module Cucumber::CiEnvironment
  extend ::Cucumber::CiEnvironment::VariableExpression

  private

  # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#24
  def detect(ci_environment, env); end

  # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#14
  def detect_ci_environment(env); end

  # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#39
  def detect_git(ci_environment, env); end

  # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#58
  def detect_revision(ci_environment, env); end

  # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#69
  def remove_userinfo_from_url(value); end

  class << self
    # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#24
    def detect(ci_environment, env); end

    # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#14
    def detect_ci_environment(env); end

    # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#39
    def detect_git(ci_environment, env); end

    # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#58
    def detect_revision(ci_environment, env); end

    # source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#69
    def remove_userinfo_from_url(value); end
  end
end

# source://cucumber-ci-environment//lib/cucumber/ci_environment.rb#10
Cucumber::CiEnvironment::CI_ENVIRONMENTS_PATH = T.let(T.unsafe(nil), String)

# source://cucumber-ci-environment//lib/cucumber/ci_environment/variable_expression.rb#5
module Cucumber::CiEnvironment::VariableExpression
  # source://cucumber-ci-environment//lib/cucumber/ci_environment/variable_expression.rb#6
  def evaluate(expression, env); end

  # source://cucumber-ci-environment//lib/cucumber/ci_environment/variable_expression.rb#36
  def get_value(variable, env); end
end
