AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - "vendor/**/*"
    - "ports/**/*"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 12

# Complexity rules are intentionally relaxed for tokenizer engine; these
# algorithms are complex by nature (parsing, UTF-8 handling, numeric
# formats).  Keep checks disabled to avoid noise while preserving other
# style checks project-wide.
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Max: 5
