require "./spec_helper"
require "./integration/backend_spec"
require "./integration/parser_spec"
require "./unit/parser_scan_spec"
require "./unit/parser_newlines_spec"
require "./unit/lexer_spec"
require "./unit/ir_spec"
